### ISSUE TITLE
Other R packages do some of this functionality

### ISSUE THREAD

**Issue by rossmounce** [helixcn/plantlist#1]
Hi Jinlong,

Have you seen the R package `taxonlookup`? https://github.com/traitecoevo/taxonlookup/

It appears to have many of the same functions as this package. Just thought you should know.

Pennell, M. W., FitzJohn, R. G., and Cornwell, W. K. 2016. A simple approach for maximizing the overlap of phylogenetic and comparative data. Methods Ecol Evol http://dx.doi.org/10.1111/2041-210x.12517

**Comment by helixcn** [comment]
Hi Ross, 

Thanks for your message. I am interested in this  package. I developed the plantlist package in 2013 but did not write any article to describe it. 

Regards,

Jinlong

**Comment by rossmounce** [comment]
Ok, just thought you might like to know
