### ISSUE TITLE
ERROR: dependency 'Rcpp' is not available for package 'plantlist'

### ISSUE THREAD

**Issue by Cactusolo** [helixcn/plantlist#2]
Try to install it with error:
package ‘Rcpp’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘Rcpp’

The downloaded binary packages are in
	C:\Users\AppData\Local\Temp\RtmpmMJVkq\downloaded_packages
"C:/PROGRA~1/R/R-35~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/AppData/Local/Temp/RtmpmMJVkq/devtools12b45c296727/helixcn-plantlist-f3e36c7"  \
  --library="C:/Users/Documents/R/win-library/3.5" --install-tests 

ERROR: dependency 'Rcpp' is not available for package 'plantlist'
* removing 'C:/Users/Documents/R/win-library/3.5/plantlist'
In R CMD INSTALL
Installation failed: Command failed (1)

##########################
I don't understand why it try to remove the pre-installed 'Rcpp'? A few of other R packages  (bindrcpp, cladoRcpp, triebeard) depended on 'Rcpp' too, so I already have 'Rcpp' installed.

Thanks fir the help!

Miao

**Comment by helixcn** [comment]
Was the Rcpp package loaded while installing the plantlist package?
Did you use `devtools::install_github("helixcn/plantlist")` in a new R session?
Sounds strange.

**Comment by Cactusolo** [comment]
yes, I used cmds:
install.packages("openxlsx")
devtools::install_github("helixcn/plantlist")


and I started it in a new session, still same issue.

BTW, I did not load any Rcpp related packages unless it automatically ran in the background.

I also tried to install "Rcpp_1.0.0.zip" came with package, got warning and error:
**cannot remove prior installation of package ‘Rcpp’**
